IMDB/IMDB/Controllers/PersonDetailsController.cs
using System.Threading.Tasks;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace IMDB.Controllers
{
    public class PersonDetailsController : Controller
    {
        private IMovie _movie { get;}
        public PersonDetailsController(IMovie movie)
        {
            _movie = movie;
        }

        public async Task<IActionResult> Index(int id)
        {
            var details = await _movie.GetPersonDetailes(id);
            details.MovieCredits = await _movie.GetCreditsByPersonId(id);
            return View(details);
        }
    }
}

IMDB/IMDB/Controllers/SearchMovieController.cs
using System.Threading.Tasks;
using IMDB.Domain.CardViewModel;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;
using static IMDB.Domain.DTOs.MovieDTO;

namespace IMDB.Controllers
{
    public class SearchMovieController : Controller
    {
        IMovie _movie;
        public SearchMovieController(IMovie movie)
        {
            _movie = movie;
        }
      
        public async Task<IActionResult> Search(string query,int mode, DiscoverFilterMovie filter, int page = 1)
        {
            ViewData["search"] = query;
            if (mode == 1)
                return RedirectToAction("index","SearchPerson",new { query = query });
            var model = new SearchViewModel();

            if (!string.IsNullOrWhiteSpace(query))
            {
                var search = new SearchMovie()
                {
                    SearchTitle = query
                };
                model.Search = search;
                model.Movies = await _movie.SearchMovies(query, 0, page);
            }
            else
            {
                filter.Page = page;
                model.Movies = await _movie.DiscoverMovie(filter);
                model.Filter = filter;
                model.Search = new SearchMovie();
            }
            return View("Index",model);
        }
    }
}

IMDB/IMDB/Controllers/SearchPersonController.cs
using System.Threading.Tasks;
using IMDB.Domain.CardViewModel;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace IMDB.Controllers
{
	public class SearchPersonController : Controller
	{
        IMovie _movie;
        public SearchPersonController(IMovie movie)
        {
            _movie = movie;
        }
        public async Task<IActionResult> Index(string query,int page = 1)
		{
            SearchPeopleViewModel model = new SearchPeopleViewModel();
            model.People = await _movie.SearchPeople(query, page);
            model.Query = query;
            model.Page = page;
			return View(model);
		}
	}
}

IMDB/IMDB/Views/SearchPerson/Index.cshtml
@using IMDB.Domain.CardViewModel
@model SearchPeopleViewModel
@section Header{

	<style>
		.li {
			margin: 10px;
		}

		.col-lg-12 {
			-webkit-box-flex: 0;
			-ms-flex: 0 0 100%;
			flex: 0 0 100%;
			max-width: 100%;
			background-color: #03092b78;
			border-radius: 15px;
			box-shadow: rgba(18, 11, 247, 0.4) 5px 5px, rgba(21, 6, 204, 0.3) 10px 10px, rgba(23, 7, 138, 0.2) 15px 15px, rgba(19, 2, 100, 0.1) 20px 20px, rgba(240, 46, 170, 0.05) 25px 25px;
			padding-bottom: 20px;
		}

		hr {
			margin-bottom: 8px;
			border-top: 1px solid #ddd;
		}

		.portfolio-menu li.active::before, .portfolio-menu li:hover::before {
			background: #313deb;
		}
	</style>
}
	<!-- breadcrumb area start -->
	<section class="breadcrumb-area">
		<div class="container">
		</div>
	</section><!-- breadcrumb area end -->
	<section class="portfolio-area pt-60">
		<div class="container">
			<form asp-controller="SearchMovie" asp-action="Search">

				<input type="hidden" asp-for="People.Page" />
				<div class="row flexbox-center">
					<div class="col-lg-6 text-center text-lg-left">
						<div class="section-title">
							<h1><i class="icofont icofont-movie"></i>Best Results For You</h1>
						</div>
					</div>
				@if (Model.People != null)
				{
					<div class="col-lg-6 text-center text-lg-right">
						<div class="portfolio-menu">
							<ul>
								<li>@Model.People.total_results Result Found </li>
							</ul>
						</div>
					</div>
				}

			</div>
			<hr />
			<div class="row">
				<div class="col-lg-12">
					<div class="row portfolio-item">
						@if (Model.People == null)
						{
							<h1>No Person Found</h1>
						}
						else
							@foreach (var cast in Model.People?.results)
							{
								<div class="col-lg-3 col-md-4 col-sm-6 popular soon TrendingDay released to">
									<a asp-controller="PersonDetails" asp-action="Index" asp-route-id="@cast.Id">
										<div class="single-portfolio">
											<div class="single-portfolio-img" id="oadAction">
												<img id="radiusprofile" src="@((string.IsNullOrEmpty(cast.ProfilePath))?"/img/cast/defult.png":"http://image.tmdb.org/t/p/w185/"+@cast.ProfilePath)" alt="dont have profile" style="border-radius: 10%;" />
											</div>
											<div class="portfolio-content">
												<h2 id="senoh">@cast.Name</h2>
												<div class="review">
													<h4>@cast.Popularity Popularity</h4>
												</div>
											</div>
										</div>
									</a>
								</div>
							}
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-3"></div>
				@if (Model.People != null && Model.People.total_results / 20 > 1)
				{
					<div class="col-sm-6">
						<div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
							<div class="btn-group">
								<ul class="pagination">
									@if (Model.People.Page > 1)
									{

										<li style="margin-top: 10%;margin-left: 2%;">
											<button asp-route-page="@(Model.People.Page-1)" class="btn btn-outline btn-primary " type="submit">
												<i class="icofont icofont-arrow-left"></i>
											</button>
										</li>
									}
									@for (int i = (Model.People.Page == 1 || Model.People.Page == 2 || Model.People.Page == 3) ? 1 : Model.People.Page - 3; i < Model.People.Page + 3 && i <= Model.People.total_pages && i < 500; i++)
									{
										<li style="margin-top: 10%;margin-left: 2%;">
											<button type="submit" asp-route-page="@(i)" class="btn btn-sm @((i != Model.People.Page)?"btn-outline-primary":"disabled btn-primary")">
												@i
											</button>
										</li>

									}
									@if (Model.People.total_pages > Model.People.Page + 2 && Model.People.Page < 500)
									{

										<li style=" margin-top: 10%;margin-left:2%;" class="text-nowrap">
											. . .
										</li>
										<li style="margin-top: 10%;margin-left: 2%;">

											<button asp-route-page="@(Model.People.total_pages > 500?500:Model.People.total_pages)" class="btn btn-outline btn-primary" type="submit">
												@(Model.People.total_pages > 500 ? 500 : Model.People.total_pages)
											</button>
										</li>
									}
									@if (Model.People.total_pages > Model.People.Page && Model.People.Page < 500)
									{

										<li style="margin-top: 10%;margin-left: 2%;">
											<button asp-route-page="@(Model.People.Page+1)" class="btn btn-outline btn-primary" type="submit">
												<i class="icofont icofont-arrow-right"></i>
											</button>
										</li>
									}

								</ul>
							</div>
						</div>
					</div>
				}

				<input type="hidden" name="query" value="@Model.Query" />
			</div>
		</form>
	</div>
</section><!-- movie section end -->