IMDB/IMDB/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Security.Claims;
using System.Threading.Tasks;
using IMDB.DataLayer.Model;
using IMDB.Domain.CardViewModel;
using IMDB.Services.Database;
using Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static IMDB.Domain.DTOs.MovieDTO;

namespace IMDB.Controllers
{
    public class ProfileController : Controller
    {
        readonly IUser _user;
        private MovieListRepo _list { get;}
        private IMovie _movie { get; }
        
        public ProfileController(IUser user, MovieListRepo list,IMovie movie)
        {
            _user = user;
            _list = list;
            _movie = movie;
        }

        public async Task<IActionResult> Index(int userId)
        {

            if(userId == 0 && !User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "SignIn");
            userId = userId == 0 ? int.Parse(User.Identity.Name): userId;
            
            ProfileViewModel model = new ProfileViewModel();
            model.IsOwner = userId == int.Parse(User.Identity.Name);
            model.User = await _user.GetUserById(userId);
            var WatchList = await _list.GetWatchListById(userId);
            List<Movie> WatchListMovies = new List<Movie>();
            foreach (var movie in WatchList)
            {
                var MovieDetail = await _movie.GetMovieById(movie.MovieId);
                if(MovieDetail != null )
                    WatchListMovies.Add(MovieDetail);
            }
            model.WatchList = WatchListMovies;

            var MovieLists = await _list.GetMovieListsById(userId);
            model.MovieLists = new List<FavouriteMovieList>();
            foreach (var list in MovieLists)
            {
                var FavouriteList = new FavouriteMovieList()
                {
                    CreateDate = list.CreateDate,
                    Id = list.Id,
                    Title = list.Title,
                    User = list.User,
                    Movies = new List<Movie>()
                };
                foreach (var movie in list.FavouriteMovies)
                {
                    var MovieDetails = await _movie.GetMovieById(movie.MovieId);
                    if (MovieDetails != null)
                        FavouriteList.Movies.Add(MovieDetails);
                }
                model.MovieLists.Add(FavouriteList);
            }

            return View(model);
        }
        [HttpPost]  
        public async Task<IActionResult> AddMovieList(string Title)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToActionPermanent("Index","SignIn");
            int userId = int.Parse(User.Identity.Name);
            await _list.AddFavouriteList(Title, userId);
            await _list.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

IMDB/IMDB/Controllers/SearchMovieController.cs
using System.Threading.Tasks;
using IMDB.Domain.CardViewModel;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;
using static IMDB.Domain.DTOs.MovieDTO;

namespace IMDB.Controllers
{
    public class SearchMovieController : Controller
    {
        IMovie _movie;
        public SearchMovieController(IMovie movie)
        {
            _movie = movie;
        }
      
        public async Task<IActionResult> Search(string query,int mode, DiscoverFilterMovie filter, int page = 1)
        {
            ViewData["search"] = query;
            if (mode == 1)
                return RedirectToAction("index","SearchPerson",new { query = query });
            var model = new SearchViewModel();

            if (!string.IsNullOrWhiteSpace(query))
            {
                var search = new SearchMovie()
                {
                    SearchTitle = query
                };
                model.Search = search;
                model.Movies = await _movie.SearchMovies(query, 0, page);
            }
            else
            {
                filter.Page = page;
                model.Movies = await _movie.DiscoverMovie(filter);
                model.Filter = filter;
                model.Search = new SearchMovie();
            }
            return View("Index",model);
        }
    }
}

IMDB/IMDB/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http.Headers;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Infrastructure;
using IMDB.Domain.CardViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;

namespace IMDB.Controllers
{
    public class SignInController : Controller
    {
        private readonly IMovie _movie;
        private readonly IUser _user;
        public SignInController(IMovie movie, IUser user)
        {
            _movie = movie;
            _user = user;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(SignInViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var user = _user.GetUserByName(model.UserName);
            if (user != null && !string.IsNullOrWhiteSpace(user.Password) && model.Password == user.Password)
            {
                UserAuthentication(user.Id, user.Name, model.RememberMe);
            }
            else
            {
                ModelState.AddModelError("Password", "نام کاربری یا رمز اشتباه می باشد");
                return View(model);
            }  
            return RedirectToAction("Index", "Home");
        }
        private List<Claim> UserAuthentication(int id, string userName, bool isRememberMe = false)
        {
            var claims = new List<Claim>()
            {
                new System.Security.Claims.Claim(ClaimTypes.Name,id.ToString()),
                new System.Security.Claims.Claim(ClaimTypes.GivenName,userName)
            };
            ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var principle = new ClaimsPrincipal(identity);
            var properties = new AuthenticationProperties()
            {
                IsPersistent = isRememberMe
            };
            HttpContext.SignInAsync(principle, properties);
            return claims;
        }

        #region Logout
        [Route("/Logout")]
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

IMDB/IMDB/Controllers/SignUpController.cs
using System;
using System.Threading.Tasks;
using IMDB.DataLayer.Model;
using IMDB.Domain.CardViewModel;
using Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace IMDB.Controllers
{
	public class SignUpController : Controller
	{
		private readonly IUser _user;
        private readonly IMovie _movie;
        public SignUpController(IUser user, IMovie movie)
		{
			_user = user;
			_movie = movie;
		}

		public IActionResult Index()
		{
			return View();
		}
		[HttpPost]
        public async Task<IActionResult> Index(SignUpViewModel model)
        {
			if (!ModelState.IsValid)
				return View(model);
			if (_user.IsUserExist(name: model.UserName))
			{
				ModelState.AddModelError("password", "Username is already registered");
				return View(model);
			}
			_user.AddUser(new User()
			{
				Name = model.UserName,
				Password = model.Password,
				RegisterDate = DateTime.Now,
				Email = model.Email,
				Phone = model.Phone
			}) ;
            return RedirectToAction("Index","SignIn");
        }
    }
}

IMDB/IMDB/Views/Shared/NetError.cshtml
<!-- breadcrumb area start -->
<section class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12" style="box-shadow: rgba(18, 11, 247, 0) 5px 5px, rgba(21, 6, 204, 0) 10px 10px, rgba(23, 7, 138, 0) 15px 15px, rgba(19, 2, 100, 0) 20px 20px, rgba(240, 46, 170, 0) 25px 25px; ">
                <div class="breadcrumb-area-content">
                    <h1>Please check your connection and try again</h1>
                </div>
            </div>
        </div>
    </div>
</section><!-- breadcrumb area end -->

IMDB/IMDB/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE HTML>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Moviepoint - Online Movie,Vedio and TV Show HTML Template</title>
	<!-- Favicon Icon -->
	<link rel="icon" type="image/png" href="/assets/img/favcion.png" />
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css" media="all" />
	<!-- Slick nav CSS -->
	<link rel="stylesheet" type="text/css" href="/assets/css/slicknav.min.css" media="all" />
	<!-- Iconfont CSS -->
	<link rel="stylesheet" type="text/css" href="/assets/css/icofont.css" media="all" />
	<!-- Owl carousel CSS -->
	<link rel="stylesheet" type="text/css" href="/assets/css/owl.carousel.css">
	<!-- Popup CSS -->
	<link rel="stylesheet" type="text/css" href="/assets/css/magnific-popup.css">
	<!-- Main style CSS -->
	<link rel="stylesheet" type="text/css" href="/assets/css/style.css" media="all" />
	<!-- Responsive CSS -->
	<link rel="stylesheet" type="text/css" href="/assets/css/responsive.css" media="all" />

	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<style>
		#f1 {
			margin-top: 20px;
		}

		#sss {
			color: white;
		}

		#qwer {
			margin: 3px;
			margin-left: 10px;
		}
		#f2{
			margin-top: 20px ;
		}

		#f3 {
			margin-top: 20px;
		}

		#f4 {
			margin-top: 20px;
		}

		#senoh {
			text-overflow: ellipsis;
			overflow: hidden;
			white-space: nowrap;
		}

		body {
			background: linear-gradient(45deg, #030810, #0e2237,#080b11);
			color: #8fb1f4;
		}

		.col-lg-12 {
			-webkit-box-flex: 0;
			-ms-flex: 0 0 100%;
			flex: 0 0 100%;
			max-width: 100%;
			background-color: #03092b78;
			border-radius: 15px;
			box-shadow: rgba(18, 11, 247, 0.4) 5px 5px, rgba(21, 6, 204, 0.3) 10px 10px, rgba(23, 7, 138, 0.2) 15px 15px, rgba(19, 2, 100, 0.1) 20px 20px, rgba(240, 46, 170, 0.05) 25px 25px;
			padding-bottom: 20px;
		}

		hr {
			margin-bottom: 8px;
			border-top: 1px solid #ddd;
		}

		.portfolio-menu li.active::before, .portfolio-menu li:hover::before {
			background: #313deb;
			z-index: 10;
		}

		.li {
			margin: 10px;
		}

		#DONTSHADOW {
			box-shadow: rgba(244, 244, 244, 0) 5px 5px, rgba(21, 6, 204, 0) 10px 10px, rgba(23, 7, 138, 0) 15px 15px, rgba(19, 2, 100, 0) 20px 20px, rgba(240, 46, 170, 0) 25px 25px;
		}

		.login-box {
			max-width: 884px;
			background: #031831cf;
			position: relative;
			color: #03090e;
			margin: 200px auto 0;
			padding: 40px 25px 25px;
			border-radius: 20px;
		}

		.login-area {
			position: fixed;
			top: -152px;
			left: 0;
			right: 0;
			margin: auto;
			display: none;
			height: 100%;
			background: rgba(0, 0, 0, 0);
			z-index: 99;
			padding: 0 15px;
		}

		#fie {
			width: 60%;
			border: none;
			height: 248px;
			margin-left: 19%;
			box-shadow: rgba(18, 11, 247, 0.4) 5px 5px, rgba(21, 6, 204, 0.3) 10px 10px, rgba(23, 7, 138, 0.2) 15px 15px, rgba(19, 2, 100, 0.1) 20px 20px, rgba(240, 46, 170, 0.05) 25px 25px;
		}

		.login-box {
			max-height: 90%;
		}

		#sec {
			margin-left: 7px;
			width: 32%;
			margin-top: 4px;
		}
	</style>
	@await RenderSectionAsync("Header", false)
</head>
<body>
	<!-- Page loader -->
	@*    <div id="preloader"></div>*@
	<!-- header section start -->
	<header class="header" style="position: absolute; background: linear-gradient(180deg, rgb(12, 0, 68) 0%, rgba(1, 1, 47, 0.88) 35%, rgba(6, 10, 15, 0) 100%); height: 202px;">
		<div id="c0" class="login-area" style="display: none;">
			<div onclick="clo()" style="width: 100%; height: 100%; position: absolute;"></div>

			<div class="login-box" id="ListVideo" style="margin-top: 16%;">
				<div>
					<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carouselk">

						<div id="carousel" class="hero-area-content">
						</div>
					</div>
					<a style="height: 79px;margin-top: 29%;background-color: #9890c157;" class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a style="height: 79px;margin-top: 29%;background-color: #9890c157;" class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</div>
		</div>



		<div class="container">
			<div class="header-area">
				<div class="logo" style="margin-top: -67px;">
					<a class="sc-iqHYGH hSaKRS imdb-header__logo-link" id="home_img_holder" asp-controller="Home" asp-action="Index" aria-label="Home">
						<img src="/assets/img/logo.png" style="max-height:70px;margin-top:30px" />
					</a>
				</div>
				<div class="header-right">
					<form asp-controller="SearchMovie" asp-action="Search" method="post">
						<div class="row" style="border: 1px solid #eee;border-radius: 30px;">

							<input type="hidden" name="page" value="1" />
							<div class="col-2">
								<select name="mode" style="opacity:0.9;">
									<option value="0">Movie</option>
									<option value="1">Cast</option>
								</select>
							</div>
							<div class="col-8">
								<input type="text" name="query" value="@ViewData["search"]" />
							</div>
							<div class="col-2">
								<input id="search-btn" type="submit" value="Search" />
							</div>
							@*<i class="icofont icofont-search" style="right: 32%; position: absolute; top: 16%;"></i>*@
						</div>
					</form>

					<ul>
						@if (User.Identity.IsAuthenticated)
						{

							<li>
								<a asp-area="" asp-controller="Profile" asp-action="Index" style="margin-left: 25px;">Welcome @(Html.Raw(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.GivenName).Value)) !</a>
							</li>
							<li>
								<a href="/Logout">Exit</a>
							</li>
						}
						else
						{
							<li><a class="theme-btn" asp-controller="SignIn" asp-action="Index" style="margin-left: 48px;">Login</a></li>
							<li><a asp-controller="SignUp" asp-action="Index">signUp</a></li>

						}


					</ul>
				</div>
				<div class="menu-area">
					<div class="responsive-menu"></div>
					<div class="mainmenu">
						<ul id="primary-menu">
							<li><a class="active" href="/">Home</a></li>
							<li><a href="/Users">Users</a></li>
							<li><a href="/PersonDetails/Index/1">Celebrity Details</a></li>
							<li><a href="/MovieDetails/Index/882598">Movie Details</a></li>
							<li><a href="/Support/Index">Support</a></li>
							<li>
								<a href="/SearchMovie/Search">Movies <i class="icofont icofont-simple-down"></i></a>
								<ul>
									<li><a href="/Home/Index#f1">Popular Movies</a></li>
									<li><a href="/Home/Index#f2">Top Rated Movies</a></li>
									<li><a href="/Home/Index#f3">Trending Movies Of Week</a></li>
									<li><a href="/Home/Index#f4">Trending Movies Of Day</a></li>
								</ul>
							</li>

						</ul>
					</div>
				</div>
			</div>
		</div>
	</header>

	@RenderBody()

	<!-- footer section start -->
	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="widget">
						<a href="/">
							<img src="/assets/img/logo.png" alt="about" />
							@*<p>7th Harley Place, London W1G 8LZ United Kingdom</p>
							<h6><span>Call us: </span>(+880) 111 222 3456</h6>*@
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="widget">
						<h4>Legal</h4>
						<ul>
							<li><a href="#">Terms of Use</a></li>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Security</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="widget">
						<h4>Account</h4>
						<ul>
							<li><a href="/Profile">My Account</a></li>
							<li><a href="/Profile#Watchlist">Watchlist</a></li>
							<li><a href="/Support/index">Support</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="widget">
						<h4>Subscribe</h4>
						<p>Sign Up in IMDb and enjoy the world of Movies , TV Shows &amp; . . . </p>
						<a href="/signup" class="theme-btn">Sign Up</a>
						<br />
						<br />
						Have an Account ? <a href="/signin" class="theme-btn">Login</a>
					</div>
				</div>
			</div>
			<hr />
		</div>
		<div class="copyright">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 text-center text-lg-right">
						<div class="copyright-content">
							<a href="#" class="scrollToTop">
								Back to top<i class="icofont icofont-arrow-up"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer><!-- footer section end -->
	<!-- jquery main JS -->
	<script src="/assets/js/jquery.min.js"></script>
	<!-- Bootstrap JS -->
	<script src="/assets/js/bootstrap.min.js"></script>
	<!-- Slick nav JS -->
	<script src="/assets/js/jquery.slicknav.min.js"></script>
	<!-- owl carousel JS -->
	<script src="/assets/js/owl.carousel.min.js"></script>
	<!-- Popup JS -->
	<script src="/assets/js/jquery.magnific-popup.min.js"></script>
	<!-- Isotope JS -->
	<script src="/assets/js/isotope.pkgd.min.js"></script>
	<!-- main JS -->
	<script src="/assets/js/main.js"></script>

	<script>
		function claoo() {
			document.getElementById("forNonn").setAttribute('style', 'display : none');

		}


		function openedit(id, name) {
			document.getElementById("modal-edit").setAttribute('style', 'display : flex');
			document.getElementById("val").setAttribute('value', id);
			document.getElementById("inp").setAttribute('value', name);
			console.log(id);
		}
		function clo() {
			document.getElementById("c0").setAttribute("style", "display: none; ");
			document.getElementById("carousel").remove();
			document.getElementById("line").remove();
		}
		function GetId(Id) {
			document.getElementById("c0").setAttribute("style", "display: block; height: 119%; background-color: #000728f0;");
			$.ajax({
				type: "GET",
				url: '/api/Api/GetOneVideoKey?id=' + Id,
				success: function (response) {
					const Array = response.split('*');
					const r = document.getElementById("carouselExampleIndicators");
					const d = document.createElement("div");
					d.setAttribute("id", "carousel");
					d.setAttribute("class", "carousel-inner");
					const g = document.createElement("ol");
					g.setAttribute("id", "line");
					g.setAttribute("class", "carousel-indicators");
					r.appendChild(g);
					r.appendChild(d);




					const carousel = document.getElementById('carousel');
					const div = document.createElement("div");
					div.setAttribute('class', 'carousel-item active');
					carousel.appendChild(div);
					const img = document.createElement("iframe");

					img.setAttribute('frameborder', "0");
					img.setAttribute('allowfullscreen', "true")
					img.setAttribute('allow', "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture");
					img.setAttribute('style', "height: 500px;");

					//     img.setAttribute('allowfullscreen');
					img.setAttribute('class', "d-block w-100");
					img.setAttribute('style', "height: 500px;");
					img.setAttribute('src', "https://www.youtube.com/embed/" + Array[Array.length - 2]);
					div.appendChild(img);
					const f = document.getElementById("line");
					const li = document.createElement("li");
					li.setAttribute("data-target", "#carouselExampleIndicators");
					li.setAttribute("data-slide-to", Array.length - 1);
					li.setAttribute("class", "active");
					li.setAttribute("data-slide-to", "0")
					f.appendChild(li);
					let counter = 2;


					while ((Array.length - counter - 1) >= 0) {
						const div2 = document.createElement("div");
						div2.setAttribute('class', 'carousel-item');
						carousel.appendChild(div2);
						const img2 = document.createElement("iframe");
						img2.setAttribute('frameborder', "0");
						img2.setAttribute('allowfullscreen', "true")
						img2.setAttribute('allow', "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture");
						img2.setAttribute('style', "height: 500px;");
						img2.setAttribute('class', "d-block w-100");
						img2.setAttribute('style', "height: 500px;");
						img2.setAttribute('src', "https://www.youtube.com/embed/" + Array[Array.length - counter - 1]);
						div2.appendChild(img2);
						const fd = document.getElementById("line");
						const lid = document.createElement("li");
						lid.setAttribute("data-target", "#carouselExampleIndicators");
						//lid.setAttribute("data-slide-to", Array.length - 1 - counter);
						lid.setAttribute("data-slide-to", counter)

						fd.appendChild(lid);
						counter++;
					}
				}
			});
		}
	</script>
	<script>
		function openo() {
			document.getElementById("forNonn").setAttribute('style', 'display : flex');
		}
	</script>
	<script>
		function closeEdit() {
			document.getElementById("modal-edit").setAttribute('style', 'display : none');

		}
	</script>
	@await RenderSectionAsync("Footer", false)

</body>

</html>